import { store } from '@/store/store'
import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'
export default function App({ Component, pageProps }: AppProps) {
  return  (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="use-credentials"/>
        <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;500&display=swap" rel="stylesheet"/>
      </Head>
    
      <Provider store = {store}>
        <Component {...pageProps} />
       </Provider>
      
    </>
  )
  
}
